### ISSUE TITLE
Input field background color should offer greater contrast with text

### ISSUE THREAD

**Issue by fturco** [projecthamster/shell-extension#100]
I recently upgraded to GNOME 3.18 and now the "What are you doing?" input field background color is dark gray instead of white. When I type something I can barely read it because of poor contrast. I have not changed theme which is still Adwaita (default light version).

![hamster](https://cloud.githubusercontent.com/assets/5459866/10605196/f65f98ac-7729-11e5-96ef-ce223b1d8939.png)

I'm using the hamster-shell-extension-git package version 20151008.g626a387-1 on a Parabola GNU/Linux-libre system.

**Comment by a-m-s** [comment]
Looks like the focus transition has stopped working.

@fturco You can fix this yourself, until the next update, by editing .local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/stylesheet.css and commenting out or deleting the five "searchEntry" styles.

In fact, I'd suggest that the fix just do that, and let the user's theme do what it does. The layout options on the table remain necessary to keep it neat.

**Comment by toupeira** [comment]
Thanks for the report & fix!

**Comment by fturco** [comment]
Upgraded to the latest git commit. It works now. Thank you!
