### ISSUE TITLE
autocomplete color in entry field unreadable

### ISSUE THREAD

**Issue by joede** [projecthamster/shell-extension#103]
With the last update of the extension, the entry field for new tasks has no longer a bright background. If I start entering a new tast, the autocomplete mechanism shows me a suggestion with a unreadable color. It is a bright green text on a white background. As soon a I move the cursor to the end of the text, it is readable again.
This makes the autocomplete useless, since I have to choose between several more or less unique task names.
I have a sceenshot, but I can't attach it to this issue ("Something went really wrong, and we can’t process that file.").

**Comment by toupeira** [comment]
Well we removed our custom styling exactly to avoid issues like these :) With Adwaita it looks fine:

![workspace 1_001](https://cloud.githubusercontent.com/assets/6501/10692437/dbc1e06c-7991-11e5-9d18-03d4cf58c984.png)

Can you post a screenshot and share what theme you're using? Use imgur.com if you can't get it to work on GitHub.

**Comment by tbaugis** [comment]
@toupeira i guess joede is on an earlier version of gnome.

the fix would be to repush the version prior to style change, then apply the style change and mark that extension is now gnome 3.18.1+ (the style change was introduced in .1) and then push that :)

**Comment by joede** [comment]
Oh sorry, I forgot to mention my environment. I'm using GNOME 1.14 from Debian 8. The theme is the original Adwaita. The entry field has the same background color and no border. Since I've forgotten the screenshot in my office, I've installed the extension on my privat notebook (Debian 8) with the same fault.

Here is the screenshot. Sorry, I don't know how to make inline images. Markdown doesn't show it.
http://up.picr.de/23483819oc.jpg

@tbaugis Does that mean there will be no fix? Which commit do you mean? My installation isn't that old, so I think it must be sometimes in summer that I've installed the extension

 I've found the commit *"Remove broken style from entry box"*. Is this the reason for my problems?

**Comment by toupeira** [comment]
@tbaugis you mean using `"shell-version": [ "3.18" ]`? Not sure if it also supports point releases, and as usual the official docs on this stuff are very incomplete :( Or do you just mean mentioning the 3.18.1 requirement in the description/README?

@joede yep b8a966a64a51640ea3e6e969b1c341a1691d8cd8 removed the custom styling of the entry box. As a quick workaround you could also add those lines back to `~/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/stylesheet.css`, but I'll definitely try for a proper fix since lots of users are still on older Gnome versions.

**Comment by joede** [comment]
@toupeira thanks for the fast answer. I'll try this at monday. And I agree to fix this for older version of GNOME too. Since I am a fan of Debian, I will always be "years" behind the *bleeding edge*. ;-)

**Comment by abhijit86k** [comment]
@toupeira and @joede I saw this issue on Debian 8 / Gnome Shell 3.14.1 too. Can confirm that reverting commit b8a966 works me.

**Comment by joede** [comment]
@abhijit86k I haven't looked at this problem for a while now. Browsing at extensions.gnome.org doesn't show me an update! I'm currently running build **18** of the hamster extension with version **26** in the `metadata.json`. This version works here with the ARC shell theme, but I can't say if this is still the commit b8a966.

**Comment by abhijit86k** [comment]
@joede I am not using the version from extensions.gnome.org. (I'm unable to install any extensions from the browser, but thats a separate problem.) I cloned this repo on my machine and followed the instructions (made a softlink in [~/.local/...](https://github.com/abhijit86k/shell-extension/tree/Colorfix#manual-installation-for-testing-and-development)). I then created a separate branch where I reverted b8a966. You can see [my branch](https://github.com/abhijit86k/shell-extension/tree/Colorfix) and compare.

**Comment by joede** [comment]
@abhijit86k I've compared my release with your branch and all JavaScript files match. Only the `metadata.json` differ. So we use the same revision. Now we have to wait for a fix. ;-)
