### ISSUE TITLE
Gnome.org shows extension is outdated.

### ISSUE THREAD

**Issue by Rastlinux** [projecthamster/shell-extension#106]
I cannot utilize this extension which I've come to heavily rely on. Any way to get ti working again or updated for the latest gnome release. Using fedora 23 and Gnome: Version 3.18.2
Thanks

**Comment by a-m-s** [comment]
It works fine in Gnome 3.18 for me (Arch). If you don't have the latest version then there should be a green upgrade button next to the "Outdated" marker on extensions.gnome.org.

**Comment by toupeira** [comment]
As @a-m-s says the "outdated" refers to the version you have installed, so please update :)
