### ISSUE TITLE
Autocomplete background color = foreground color => unreadable

### ISSUE THREAD

**Issue by cebe** [projecthamster/shell-extension#107]
I have the following issue with the autocomplete:

![bildschirmfoto von 2016-01-27 13 44 26](https://cloud.githubusercontent.com/assets/189796/12613790/329f054e-c4fc-11e5-93fb-6e93feab9e05.png)

The white bar is, what has been added by autocomplete while I type.

**Comment by a-m-s** [comment]
The colours are supposed to be defined by your Gnome theme.

What version of Gnome do you have, and is the plugin up to date?

**Comment by cebe** [comment]
I am using the gnome shell from debian jessie:

```
$ dpkg -l |grep gnome-shell
ii  gnome-shell                            3.14.4-1~deb8u1                      amd64        graphical shell for the GNOME desktop
```

the extension is the latest code from master of this repository.

**Comment by a-m-s** [comment]
I can confirm that I see the same in a fresh install of Debian Jessie.

**Comment by a-m-s** [comment]
I downloaded a random theme from gnome-look.org (GNOME Shell category), unpacked it into `~/.themes`, opened Tweak Tool and set the Shell theme, and the problem is solved.

It seems like the default theme in 3.14 just isn't very good. (3.18 is fine; not sure which others are broken.)

**Comment by cebe** [comment]
okay, seems I need to report this elsewhere then. Thanks for checking!
