### ISSUE TITLE
New look'n'feel

### ISSUE THREAD

**Issue by jplorier** [projecthamster/shell-extension#109]
Hi,

I have Fedora 23 with gnome-shell 3.18 and in my opinion, though new look is nice, the functionalities that were lost in the version of hamster extension are not worth the look.
I can't now just select the time range in the add earlier task and it seems that the syntax task@category, description #label is no longer working, everything after the comma is lost.
Is there a new syntax? Do I have to enter the time range by hand now? is there a chance that those things can be back?
Regards

**Comment by a-m-s** [comment]
The "Add Earlier Activity" window is not part of the shell extension; that's in the main Project Hamster application (the extension just sends an open request). However, range selection works fine for me.

The comma and #label syntax should work and has not changed for a long while now. Did you just do a big update from something very old?

**Comment by jplorier** [comment]
I just did a fedora upgrade from 22 to 23. The starting point was a
fedora 22 up to date, so it shouldn't have been a big jump.
I continued to use the syntax as used but yesterday when I looked at the
summary, I found that every entry had just the part prior to the comma,
the rest is gone.
Regards

**Comment by a-m-s** [comment]
I think you need to better describe, perhaps with screen shots, where you are typing and show what's wrong with range entry.

**Comment by cebe** [comment]
Just tried to enter the following for a new task: `test@testcat, mydescription #test`
and it generated a task "test@testcat" with description "mydescription" and added a tag `test`. That is what would be expected imo.

I am using `gnome-shell 3.14.4-1~deb8u1` with the latest version of this repository. What are your versions?

**Comment by jplorier** [comment]
I'm using gnome-shell 3.18.4-1 fedora 23.
I'll upload images as requested

**Comment by jplorier** [comment]
http://picpaste.com/Captura_de_pantalla_de_2016-03-22_11-03-06-x6wC0SZn.png
http://picpaste.com/Captura_de_pantalla_de_2016-03-22_11-03-59-eN3HRNvF.png

**Comment by cebe** [comment]
@jplorier the screenshots do not show this extension but hamster application itself...

**Comment by a-m-s** [comment]
And it's not the latest release (1.04 Jan 2014). It might be a development snapshot from something newer?

Please check the version number and post a bug at https://github.com/projecthamster/hamster

**Comment by a-m-s** [comment]
This is not the proper place, but, just FYI, I installed the development sources of the main hamster app, and I do not see any problem with commas and descriptions. I do see that the draggable range feature is missing, and there are other changes I'd perhaps like undone, but as yet the only proper bug is the missing data in the exports (already reported).

**Comment by a-m-s** [comment]
Now I understand: it's not about creating a task with a description, it's about adding a description to an existing task.

That is https://github.com/projecthamster/hamster/issues/305
