### ISSUE TITLE
Extension doesn't work on wayland

### ISSUE THREAD

**Issue by ntkoopman** [projecthamster/shell-extension#115]
Using Fedora 24 with a Wayland session:

Gio.IOErrorEnum: Error calling StartServiceByName for org.gnome.Hamster.WindowServer: Timeout was reached

**Comment by fosero** [comment]
This suddenly started working for me again in 3.22

**Comment by elbenfreund** [comment]
Thanks for the heads up. I will close this for now. Please feel encouraged to reopen if the issue persists.

**Comment by ntkoopman** [comment]
It doesn't work in Fedora 25 either.
The problem is that de DBus service doesn't get started. After you start it (either manually or by starting an Xorg session first) the extension works correctly.

**Comment by a-m-s** [comment]
Works fine on Arch with Wayland, both Gnome 3.20 and 3.22. Presumably the DBus issue is not directly related to Wayland.

**Comment by hedayat** [comment]
> It doesn't work in Fedora 25 either.
> The problem is that de DBus service doesn't get started. After you start it (either manually or by starting an Xorg session first) the extension works correctly.

I have the same problem, except that starting and Xorg session and then logging out and logging in under Wayland doesn't solve the problem. However, if after logging in I run hamster application and lock & unlock the screen, the extension starts to work correctly.
