### ISSUE TITLE
Gnome 3.21 Debian Stretch Not working

### ISSUE THREAD

**Issue by marxistvegan** [projecthamster/shell-extension#151]
Hey folks, love this extension and use hamster every day. However since upgrade to gnome shell 3.21 in Debian stretch this is not longer working. 
 Has anyone else run into this problem?

**Comment by cebe** [comment]
> this is not longer working

can you be more specific about how exactly it is not working?

**Comment by thePanz** [comment]
The shell extension is not shown, and the extensions list displays: "Extension does not support shell version".

I tried to update the `metadata.json` by adding the new `3.21` version, but without luck.

**Comment by thePanz** [comment]
I was able to fix it :)
See: https://github.com/projecthamster/shell-extension/pull/152

**Comment by marxistvegan** [comment]
confirmed #152 fixes is it...closing this
