### ISSUE TITLE
Error installing extension Ubuntu 18.04

### ISSUE THREAD

**Issue by mordax7** [projecthamster/shell-extension#284]
I have an issue installing the extension on my Ubuntu 18.04, I have the `hamster-service` and `hamster-windows-service` running but after many retries, I was not able to install it.

My `ps` command:

> agantar@agantar-XPS-13-9360:~$ ps aux | grep hamster
> agantar   2857  0.0  0.2 414744 35060 ?        Sl   13:08   0:00 /usr/bin/python /usr/lib/hamster-applet/hamster-service
> agantar   2909  0.0  0.2 583296 44768 ?        Sl   13:09   0:00 /usr/bin/python /usr/lib/hamster-applet/hamster-windows-service
> agantar   7241  0.0  0.0  21540  1052 pts/0    S+   14:08   0:00 grep --color=auto hamster

My logs:

> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]: Archive:  /tmp/VXZNIZ.shell-extension.zip
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/stylesheet.css
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/nl/LC_MESSAGES/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/pl/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/pt-BR/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/README.md
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/pt-BR/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/de/LC_MESSAGES/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/es/LC_MESSAGES/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/cs/LC_MESSAGES/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/ru/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:    creating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/images/
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/de/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/ru/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/cs/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/cs/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/fr/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/schemas/org.gnome.shell.extensions.project-hamster.gschema.xml
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/stuff.js
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/es/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/pl/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/schemas/gschemas.compiled
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/build.sh
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/convenience.js
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/nl/LC_MESSAGES/hamster-shell-extension.po
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/fr/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/extension.js
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/CHANGES
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/prefs.js
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/images/hamster-idle-symbolic.svg
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/nl/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/es/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/images/hamster-tracking-symbolic.svg
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:   inflating: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/locale/de/LC_MESSAGES/hamster-shell-extension.mo
> May 16 14:08:41 agantar-XPS-13-9360 org.gnome.Shell.desktop[1769]:  extracting: /home/agantar/.local/share/gnome-shell/extensions/hamster_sufiyan@projecthamster.wordpress.com/metadata.json
> May 16 14:08:41 agantar-XPS-13-9360 gnome-shell[1769]: Extension "hamster_sufiyan@projecthamster.wordpress.com" had error: SyntaxError: redeclaration of let fact
> May 16 14:08:41 agantar-XPS-13-9360 gnome-software[1995]: no app for changed hamster_sufiyan@projecthamster.wordpress.com

JS error:
>   SyntaxError: redeclaration of let renderer
>   
>   Stack trace:
>   
>   _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
>   @<main>:1:43

**Comment by elbenfreund** [comment]
Hi there :)
Are you running the version from the `develop` branch or the latest on EGO?

**Comment by mordax7** [comment]
Hei :)

I am installing the compiled version on the gnome extension site: https://extensions.gnome.org/extension/425/project-hamster-extension/
I am not sure which branch its using.

Should I compile the sources from the 0.10.0 release?

**Comment by elbenfreund** [comment]
Im am confident that using `0.10.0` will solve your problem. There is a convenient `make` target that should make this rather easy. for details please see the readme. :)
Good luck.

**Comment by mordax7** [comment]
Works like a charm, thank you for your help.
May close the issue.
