### ISSUE TITLE
Super + H shortcut overrides Gnome Shell minimize

### ISSUE THREAD

**Issue by cas--** [projecthamster/shell-extension#286]
I think there should be a different default Hamster keyboard shortcut as `Super + H` is already taken by Gnome Shell: https://wiki.gnome.org/Design/OS/KeyboardShortcuts

Perhaps `Super + Shift + H` or `Super + Crtl + H`

**Comment by rhertzog** [comment]
Personally I use "Super + T" with T for "Time Tracking". When you use a time tracker, you have to call it frequently, it's best to have an easy to type shortcut.
