### ISSUE TITLE
frequently crashes shell (3.26.2) on changing activity

### ISSUE THREAD

**Issue by jmberg** [projecthamster/shell-extension#288]
This happens very frequently for me (every few changes of activity), but I have no idea how to debug.

I'm running the latest afaict (commit 0d815b26ec2d) and can easily upgrade/debug/etc. if you tell me how - I'm proficient in C and debugging in general, but know next to nothing about shell extensions.

**Comment by wolffi** [comment]
Same here. I run fedora 28 with gnome-shell 3.28.2, hamster-shell-extension crashes gnome-shell on every other change of activity or so.

**Comment by chama-chomo** [comment]
same here, fedora 28

**Comment by mgoppold** [comment]
as well as openSUSE Leap 15.1

```
Jul 31 12:57:24 myhost gnome-shell[21106]: JS WARNING: [/home/mgoppold/.local/share/gnome-shell/extensions/contact@projecthamster.org/extension.js 223]: reference to undefined property "activities"
Jul 31 12:57:24 myhost gnome-shell[21106]: ACTIVITIES HAMSTER: , 
Jul 31 12:57:24 myhost gnome-shell[21106]: GNOME Shell started at Wed Jul 31 2019 12:57:21 GMT+0200 (CEST)
```

with

- hamster-time-tracker-2.2.2-lp150.33.1.noarch
- gnome-shell-extension-hamster-2.2.20.10.0-lp150.33.1.noarch

**Comment by mwilck** [comment]
Please test with `gnome-shell-3.28` or one of the later code bases matching your GNOME version (see https://github.com/projecthamster/hamster-shell-extension/tags).

**Comment by DirkHoffmann** [comment]
@jmberg, @chama-chomo, are you still on **fedora28**? Solutions are reported to work on **fedora30** and **fedora31**. So we would like to close this within two weeks, unless needed otherwise.

Are two weeks for feedback also OK for you, @mgoppold?
Anyway, issues can be re-opened.

**Comment by jmberg** [comment]
I'm on 31 now. I was on 29 far too long/late due to some work packages, but never much on 28, IIRC. Certainly not now.

Actually, it doesn't crash for me these days. I vaguely remember something in this area but I'd have to dig. Right now I'm on gnome 3.34.4 and hamster-extension 3c320e9d73ac.

**Comment by jmberg** [comment]
I have a vague feeling it might somehow have been related to " factsBox: use GObject.registerClass()" or such, but TBH I really don't know right now. I'll try to dig out more later, if I can.

**Comment by chama-chomo** [comment]
Hi, I'm not with Fedora and even Hamster anymore. Good to hear you were able to fix it, though.

**Comment by DirkHoffmann** [comment]
> @jmberg, @chama-chomo, are you still on **fedora28**? Solutions are reported to work on **fedora30** and **fedora31**. So we would like to close this within two weeks, unless needed otherwise.

Thank you very much for your quick feedback, @jmberg, @chama-chomo!
I just noticed I forgot to "ring" @wolffi (same request for feedback, please).

**Comment by jmberg** [comment]
hasn't happened to me in ages
