### ISSUE TITLE
Not working with gnome-shell 3.32 under fedora 30

### ISSUE THREAD

**Issue by DirkHoffmann** [projecthamster/shell-extension#301]
I am glad to see that there are error reports (at least one: #295) concerning gnome-shell 3.30, and they are accepted. 

Are the statements that [3.26 is the latest](https://extensions.gnome.org/extension/425/project-hamster-extension/) or [3.28 as in the README](../blob/develop/README.rst) then obsolete? (I can provide a PR for the latter, but not the former, if you confirm.)

**Comment by gregorydk** [comment]
It's 3.30, the extension doesn't work in 3.31 any more. I'm a sad panda now.

**Comment by DirkHoffmann** [comment]
Good. 3.30 is the one in my distro.
I updated your README.st (PR #303). Please act as like you feel. (And don't forget to update https://extensions.gnome.org/extension/425/project-hamster-extension/ as well.)

So this question is settled, and my initial request becomes: Why does it not work on my system. ;-) 
What can I do to debug the situation? I can launch `hamster` on my system and see the corresponding window, but nothing like 
![this](https://extensions.gnome.org/extension-data/screenshots/screenshot_425.png)
Should a text like "Hamster 02:52" appear in the top bar?

**Comment by DirkHoffmann** [comment]
Still true for 3.32 / Fedora 30 today. 
Nothing is displayed at all.

**Comment by DirkHoffmann** [comment]
May be a duplicate of #315.

**Comment by gregorydk** [comment]
@DirkHoffmann https://github.com/mwilck/hamster-shell-extension should work on 3.34.

**Comment by DirkHoffmann** [comment]
> https://github.com/mwilck/hamster-shell-extension should work on 3.34.

Thank you, @gregorydk. But this is about 3.32. 
However, @mwilck's [GNOME-3.32 branch](https://github.com/mwilck/hamster-shell-extension/tree/GNOME-3.32) worked fine for me. I can live with it.

The problem is that the standard distribution path (for gnome-shell extensions) is broken, this repository is not up to date (since April 2019) and manual installation bears a number of pitfalls (the [README](../blob/master/README.rst#manual-installation-for-testing-and-development) is wrong as of today).
That's why I leave this issue open.

**Comment by gregorydk** [comment]
@DirkHoffmann I thought you'd already be running Fedora 31. ;-)

**Comment by ederag** [comment]
@DirkHoffmann 
> manual installation bears a number of pitfalls (the README is wrong as of today).

Care to elaborate ? At least [two of us](https://github.com/projecthamster/hamster/issues/433#issuecomment-591932703) have trouble installing the extension from sources.

The extension does not show up anywhere on screen on lubuntu-19.04, even after doing
```bash
> gnome-shell --version
GNOME Shell 3.32.2

git clone https://github.com/mwilck/hamster-shell-extension.git
# GNOME-3.34  was not better
git checkout GNOME-3.32
make dist
rm -rf ~/.local/share/gnome-shell/extensions/contact@projecthamster.org
mkdir -p ~/.local/share/gnome-shell/extensions/contact@projecthamster.org
tar -C ~/.local/share/gnome-shell/extensions/contact@projecthamster.org \
     -xvf dist/contact@projecthamster.org.tgz
# reload shell (on xorg; on wayland one needs to logout/login): ALT+F2, r, Enter

> sudo apt install gnome-tweak-tool
Unpacking gnome-tweaks (3.32.0-1)
> gnome-tweaks
```
The extension is listed, checked (blue) at the first tentative, 
but closing and reopening `gnome-tweaks`:
![Screenshot_20200227_172853](https://user-images.githubusercontent.com/10962809/75463839-a19afc00-5986-11ea-9f41-acdf871605c2.png)

**Comment by didierm** [comment]
Works for me in Gnome 3.34 : https://github.com/projecthamster/hamster/issues/433#issuecomment-591952169

Possible diagnostics : 
* `sudo journalctl -fel /usr/bin/gnome-shell`
and 
* Gnome Looking Glass ([ALT]+[F2] > "lg" > [Extensions])

**Comment by ederag** [comment]
`sudo apt install gnome-shell-extensions` helped; now the hamster-shell-extension has no error.
It is checked in the `gnome-tweaks`, and there are no errors in the Gnome Looking Glass 
(thanks for the tips !)
![Screenshot_20200227_194912](https://user-images.githubusercontent.com/10962809/75476162-686c8700-599a-11ea-9195-5353eef25ac5.png)

`sudo journalctl -fel /usr/bin/gnome-shell`
showed errors prior to the `gnome-shell-extensions` installation. But now there is only:
```
févr. 27 17:43:30 lubuntu-1904-vb gnome-shell[677]: GNOME Shell started at Thu Feb 27 2020 17:43:29 GMT+0100 (CET)
févr. 27 17:43:38 lubuntu-1904-vb org.gnome.Shell.desktop[677]: Window manager warning: Buggy client sent a _NET_ACTIVE_WINDOW message with a timestamp of 0 for 0x2e00007
```
But nothing shows up. It should be at the top, right ?

**Comment by DirkHoffmann** [comment]
All the above is correct.
I have no better recipe [than the one above](https://github.com/projecthamster/hamster-shell-extension/issues/301#issuecomment-592053543). 

For the time being, four people were found to pick up the orphaned repository [hamster-shell-extension](https://github.com/projecthamster/hamster-shell-extension). Please give us a couple more days to integrate the [good work](https://github.com/mwilck/hamster-shell-extension/) by @mwilck  into the main repository and start from solid grounds again.
Individual care would be counterproductive at present, I am afraid. Sorry!

**Comment by DirkHoffmann** [comment]
Picking this up from the other ticket for memory:

_Originally posted by @mwilck in https://github.com/projecthamster/hamster-shell-extension/issues/315#issuecomment-593488824_

> Could you provide some more info, e.g. `journalctl --user -b` output, from running the 3.34 code in under 3.32?

and

> @DirkHoffmann, could you try if reverting 69af56af fixes the issue on GNOME 3.32?

**Comment by mwilck** [comment]
> > @DirkHoffmann, could you try if reverting [69af56a](https://github.com/projecthamster/hamster-shell-extension/commit/69af56aff2e49cf8888f70a761bfa281ad48ef95) fixes the issue on GNOME 3.32?

The commit ID to be reverted would now be 85d09e2, as I've re-posted PR #316 with new commit IDs (signed commits).

**Comment by mwilck** [comment]
@DirkHoffmann, IIUC this is fixed? Please confirm and close.

**Comment by DirkHoffmann** [comment]
Yes, there were many duplicate and redundant issues for gnome-shell > 3.28, and we lost slightly track. I do not the check the relationships and history exactly. But as this was oriniginally reported by me, I take the freedom to close it (satisfied).
