### ISSUE TITLE
Build fails after convenience.js has been removed from gnome-shell-extension repository

### ISSUE THREAD

**Issue by ofurkusi** [projecthamster/shell-extension#306]
The file `convenience.js` which is downloaded in line 59 of the Makefile no longer exists in the `master` branch of the gnome-shell-extension repository. The file was removed with the following commit:

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/commit/bab4be1a597226a5fe8a29dcf3848be47e16a5e5 

The build fails with the following error message:
> Connecting to gitlab.gnome.org (gitlab.gnome.org)|209.132.180.181|:443... connected.
> HTTP request sent, awaiting response... 404 Not Found
> 2019-03-20 21:51:42 ERROR 404: Not Found.
> 
> make: *** [Makefile:59: collect] Error 8

Referring instead to the latest revision of the file in the Makefile seems to work:
https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/47beeb1a8e9afba410dc7587cb40f7fb00f5e3a7/lib/convenience.js

**Comment by akvadrako** [comment]
Here is the needed patch:
```diff
diff --git a/Makefile b/Makefile
index b298126..311ba6e 100644
--- a/Makefile
+++ b/Makefile
@@ -56,7 +56,7 @@ collect:
 	mkdir -p $(BUILDDIR)
 	cp -R extension/* $(BUILDDIR)
 	cp -R data/* $(BUILDDIR)
-	wget https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/master/lib/convenience.js -O $(BUILDDIR)/convenience.js
+	wget https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/47beeb1a8e9afba410dc7587cb40f7fb00f5e3a7/lib/convenience.js -O $(BUILDDIR)/convenience.js
 
 compile: collect
 	glib-compile-schemas $(BUILDDIR)/schemas
```

**Comment by DirkHoffmann** [comment]
You may want to look at #302. The file `convenience.js` is not needed any more.

Or specify, which version of (older?) gnome-shell you need to use.

**Comment by mwilck** [comment]
See 1424cc9, from #316. Similar to @akvadrako's suggestion. I believe this can be closed.

**Comment by DirkHoffmann** [comment]
So be it closed.

Thanks for reporting and proposing, @ofurkusi and @akvadrako, Sorry for the delayed answer and hope to see you soon.
