### ISSUE TITLE
Interferes with screen lock with GNOME shell 3.30.2 on Debian Buster (10)

### ISSUE THREAD

**Issue by slaufmann** [projecthamster/shell-extension#311]
I really love the simple approach of project hamster and would like to use the shell extension.
Unfortunately it does not quite work with gnome-shell 3.30.2.

I've built the extension from the develop branch at commit 0d815b26ec2df0fe3c65ec5c614c416634e8d4c9 and needed to edit the metadata.json so i could install the extension on GNOME shell 3.30.

But now I encounter similar issues as described in #300 and #295.
Are the changes proposed in these issues already merged to the develop branch?

If I could provide further information from my side I am happy to do so. Thanks.

**Comment by mwilck** [comment]
Have you tried @heyadat's code base, or mine?

**Comment by slaufmann** [comment]
I cloned the repo, checked out the develop branch and built it as of commit 0d815b26ec2df0fe3c65ec5c614c416634e8d4c9 .
Further than that I don't quite know whose code base this is?

**Comment by mwilck** [comment]
> Further than that I don't quite know whose code base this is?

Various people have contributed. @hedayat and myself, for example. My personal recommendation for you is [my GNOME-3.30 branch](https://github.com/mwilck/hamster-shell-extension/tree/GNOME-3.30). it's the code shipped in openSUSE Tumbleweed (but about to be replaced with 3.32-compatible code). The main repo is moving a bit slowly these days, and unfortunately, incompatibilities keep popping up with every new GNOME release.

**Comment by slaufmann** [comment]
Thank you, your branch builds and runs fine until now.
