### ISSUE TITLE
Manual install fails on Ubuntu 18.04, Gnome 3.28

### ISSUE THREAD

**Issue by LM-HZG** [projecthamster/shell-extension#337]
Hello there,

I'm having troubles to install the extension for Gnome 3.28. I tried the following two approaches following the Readme:

1. manually download and install
- download [latest commit](https://github.com/projecthamster/hamster-shell-extension/commit/16b7a0e32d37257e48defe1f65f1d72badb0be2b) for Gome Shell version 3.28 from Releases
- extract and enter folder
- execute make dist
- Result:

> rm -fr build
> mkdir -p build
> cp -R extension/* build
> cp -R data/* build
> wget https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/master/lib/convenience.js -O build/convenience.js
> --2020-10-23 09:22:06--  https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/master/lib/convenience.js
> Auflösen des Hostnamens gitlab.gnome.org (gitlab.gnome.org) … 2620:52:3:1:5054:ff:fe8f:413d, 8.43.85.27
> Verbindungsaufbau zu gitlab.gnome.org (gitlab.gnome.org)|2620:52:3:1:5054:ff:fe8f:413d|:443 … verbunden.
> HTTP-Anforderung gesendet, auf Antwort wird gewartet … 502 Bad Gateway
> 2020-10-23 09:22:07 FEHLER 502: Bad Gateway.
> 
> Makefile:56: recipe for target 'collect' failed
> make: *** [collect] Error 8  

2. Deploy via Git
- `git clone https://github.com/projecthamster/hamster-shell-extension.git`
- `cd hamster-shell-extension/`
- `git checkout 0d815b26ec2df0fe3c65ec5c614c416634e8d4c9`
> …  
> HEAD ist jetzt bei 0d815b2 Merge branch 'release/0.10.0'
- `make dist` leads to the same result as above

Obviously the installation lacks a build/convenience.js. Any ideas?

**Comment by LM-HZG** [comment]
**Update:**

- omitting line …
> wget https://gitlab.gnome.org/GNOME/gnome-shell-extensions/raw/master/lib/convenience.js -O $(BUILDDIR)/convenience.js
…(file does not exist anymore) in collect section of the makefile lets the make routine finish the task, and the respective tarballs and zips are created
- unpacking with `tar xfz dist/contact@projecthamster.org.tgz -C ~/.local/share/gnome-shell/extensions/contact@projecthamster.org` (Not that the readme states "…projecthamster.org.**tar.gz**…") and refreshing the shell makes the extension available in the *tweak* tool. However, opening the preferences returns an error and stack trace related to the missing convenience.js. and activating the extension seems to do nothing. No icon displayed, no error message.

- searched for convenience.js in https://gitlab.gnome.org/GNOME/gnome-shell-extensions/ and found one [here](https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/blob/gnome-3-28/lib/convenience.js). 
- Replacing the above link with this one in the makefile results in a seemingly successful build.  
- However, clicking the preferences button in gnome-tweak returns this:
> SyntaxError: expected expression, got '<'
> 
> Stack trace:
>   @/home/user/.local/share/gnome-shell/extensions/contact@projecthamster.org/prefs.js:33:7
>   _getExtensionPrefsModule@resource:///org/gnome/shell/extensionPrefs/main.js:75:13
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _selectExtension@resource:///org/gnome/shell/extensionPrefs/main.js:90:31
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   _onCommandLine@resource:///org/gnome/shell/extensionPrefs/main.js:243:17
>   wrapper@resource:///org/gnome/gjs/modules/_legacy.js:82:22
>   main@resource:///org/gnome/shell/extensionPrefs/main.js:397:5
>   @<main>:1:43

Any hint would be appreciated!

**Comment by LM-HZG** [comment]
For the sake of completeness - the same errors occur following the instructions in #327 with the file linked for 3.28.

**Comment by hedayat** [comment]
The mentioned file is no longer needed for more recent Gnome vesions; so, you should download the one for gnome 3.28.

You can use this URL instead of the original one:

https://gitlab.gnome.org/GNOME/gnome-shell-extensions/-/raw/gnome-3-28/lib/convenience.js

**Comment by LM-HZG** [comment]
That worked! Thanks for pointing me to the right file @hedayat

**Comment by hedayat** [comment]
:) You're welcome
