### ISSUE TITLE
Gnome 3.38 compatibility and Testing Help

### ISSUE THREAD

**Issue by faebser** [projecthamster/shell-extension#338]
Hi guys,

I was wondering if there is a way to gnome 3.38 compatibility? I would also love to help out with testing and giving feedback.

Thanks

**Comment by rhertzog** [comment]
The extension does work with GNOME 3.38 without any change. We just need to bump the data in data/metadata.json.in.

**Comment by faebser** [comment]
Thank you, it works now.

Is there stuff to test?
