### ISSUE TITLE
Provide 3.38 tag 

### ISSUE THREAD

**Issue by camlafit** [projecthamster/shell-extension#347]
Hello

Since 89a93f4dcbefb40b00c1eda4b33114112d7c8b51 , develop version looks compatible with 3.38 gnome. Should be nice to 
update #327 and add gnome-shell-3.38 tag or at least allow update from https://extensions.gnome.org/

Thanks

**Comment by rrthomas** [comment]
Similarly now for GNOME 42!

**Comment by mwilck** [comment]
We can't update extensions.gnome.org. Only @elbenfreund would be able to do that.

**Comment by rrthomas** [comment]
Ah, thanks!

**Comment by mwilck** [comment]
Done.

**Comment by hedayat** [comment]
Thanks Martin for the fix. But, maybe its time for us to somehow push the new version without waiting for @elbenfreund  anymore. For example by adding a number at the end as a new extension.
