### ISSUE TITLE
Cannot edit hotkey in prefs

### ISSUE THREAD

**Issue by rrthomas** [projecthamster/shell-extension#350]
On GNOME 42, when I edit the hotkey in the prefs in Extension Manager, whatever I type as the new hotkey combination is replaced by the string `0x1`, which looks like some kind of error code.

If I edit the hotkey pref directly in dconf, then it takes effect as expected.

Thanks for hamster-shell-extension! I was relieved to find it has been updated for GNOME 42 when I upgraded just now.

**Comment by mwilck** [comment]
Thanks for the report. It seems that `Gtk.accelerator_parse()` has changed its return value
  - [Gtk3](https://gjs-docs.gnome.org/gtk30~3.24.34/gtk.accelerator_parse)
  - [Gtk4](https://gjs-docs.gnome.org/gtk40~4.6.6/gtk.accelerator_parse)

Strangely, `Gtk.MAJOR_VERSION` is different in the extension itself and in `lg`.

**Comment by mwilck** [comment]
Please test the code from #351.
