### ISSUE TITLE
Problems entering previous activities

### ISSUE THREAD

**Issue by AHeinlein** [projecthamster/shell-extension#356]
I have found several difficulties entering previous activities.

**The first issue** is with time selection - I have attached two screenshots showing the problem. The screens were made today at 14:27. I chose 07:15 as the start time. In the "End time" field, I get "14:42 (15 min)" as the first option, no earlier times - obviously calculated based on "now" instead of the start time.

![Bildschirmfoto von 2023-02-24 14-27-25](https://user-images.githubusercontent.com/22483295/221201739-2ffe3493-f751-4e47-983e-b489dc8aba10.png)
 
If I manually enter e.g. "08:15" as the end time, the date is automatically moved forward to the next day, saturday 02/25 in this case. Only after correcting this to friday 02/24, I can finally enter the time period I want.

![Bildschirmfoto von 2023-02-24 14-28-09](https://user-images.githubusercontent.com/22483295/221201733-e38efd70-c781-4272-93b8-11e5bc4b487b.png)

**The second issue** is with selecting activities from the list - the list is always empty and I have to choose "Show all activities" first before I can select anything.

I am using Debian 11 with Gnome Shell 3.38. I tried both the debian packaged version (from git 20200509) as well as the latest tagged "3.38" from GitHub.

**Comment by mwilck** [comment]
The screenshots are from hamster itself, not from the shell extension. You should file this against projecthamster/hamster. Make sure you are using the latest version. Some issues with time entry have been fixed a while ago.
