### ISSUE TITLE
Add Gnome 46 Compatibility!

### ISSUE THREAD

**Issue by hedayat** [projecthamster/shell-extension#366]
Well, this time of year again :)

Turns out that the extension doesn't work with Gnome 46 too (yeah, after increasing the compatibility version to 46 in metadata.json). When started, it generates an error message:

```
Connection to DBUS service failed
TypeError: _actor.add_actor is not a function
```

**Comment by mwilck** [comment]
#367 and #364 have now been merged into the "develop" branch.
