### ISSUE TITLE
Tags don't appear to work properly

### ISSUE THREAD

**Issue by shaneonabike** [projecthamster/shell-extension#75]
Hey there!

This is a super awesome extension for gnome thanks for working on it. I checked out the README but I couldn't see any documentation on exactly how one should use it.

In the main interface I have several activities associated to specific parent item. So for example project1@projects. Then I tag the various projects I am working on in order to categorize my work.

In the main interface it would be
* Activity: project1@Projects
* Tags: Content

But I cannot for the life of me determine how to reference tags from the applet. I figured out how to associate an activity well.

I'm using the latest version available for Ubuntu Gnome 13.04

Thanks very much

**Comment by elbenfreund** [comment]
Seems to be solved.
