### ISSUE TITLE
The extension fails to load at log-in

### ISSUE THREAD

**Issue by a-m-s** [projecthamster/shell-extension#77]
I usually have to restart gnome-shell (Alt-F2, r) to get the extension to appear.

"Time Tracker" is one of the "Startup Applications" listed by Tweak Tool, and that works fine. I presume there's a race-condition or startup-ordering problem, but I've not confirmed it.

I have Gnome 3.12 on Arch, and the extension from Git.

**Comment by toupeira** [comment]
Closing this, feel free to reopen if you still experience this.

**Comment by a-m-s** [comment]
Sorry, I should have closed this myself. The root cause turned out to be a corrupt file system causing things to load slowly. I've no idea why it had this specific effect (so there may be a bug somewhere), but probably it was just a timeout. After reformat, and restore from backup, all is well.
