### ISSUE TITLE
Extension doesn't work with 3.16

### ISSUE THREAD

**Issue by tbaugis** [projecthamster/shell-extension#89]
this is a preemptive report as i won't be running 3.16 myself until fedora's beta comes out.

If somebody's actually already running 3.16, please check if it works straight out of the box:
simply add "3.16" here https://github.com/projecthamster/shell-extension/blob/master/metadata.json#L14 and  report back!

**Comment by jhass** [comment]
No apparent issues here, tested on Archlinux, Gnome 3.16 from testing, elegance-colors shell theme and in a Wayland session.

**Comment by toupeira** [comment]
Seems to work fine according to PR https://github.com/projecthamster/shell-extension/pull/90, new version is pending at https://extensions.gnome.org/review/4776.
