### ISSUE TITLE
Please display list of today's activities scrolled to bottom by default

### ISSUE THREAD

**Issue by rrthomas** [projecthamster/shell-extension#92]
The list of today's activities is currently shown with the scrollbar at the top by default, which confused me the first time as before I noticed the scrollbar I couldn't see my most recent activities. After I noticed it I kept having to scroll down to check my most recent activities (I suspect usually the most interesting part of the list!).

**Comment by toupeira** [comment]
Thanks for the report, this was bugging me as well everytime I ran into it :) New release will be on extensions.gnome.org shortly!

**Comment by rrthomas** [comment]
Thanks very much for this, I look forward to the new release. I started using your shell extension only today, after using hamster-indicator for a long time, and I couldn't get the indicator's global hot-key to work, but the extension worked immediately, so great stuff!
