### ISSUE TITLE
Please update for gnome 3.18

### ISSUE THREAD

**Issue by jehane** [projecthamster/shell-extension#96]
Gnome 3.18 is out and distribution will soon follow. Can you update the extension for the new gnome ? 
Thanks

**Comment by toupeira** [comment]
Can anybody verify if the extension still works with Gnome 3.18? You can try it out by adding `3.18` to the list of supported versions in https://github.com/projecthamster/shell-extension/blob/bcc9c1ff7325c4b2fd98928bfa89704a13f37857/metadata.json#L11-L16

**Comment by jehane** [comment]
I have try and it fail

**Comment by toupeira** [comment]
Do you see any relevant error messages in `~/.xsession-errors` or with `journalctl -f` when restarting Gnome-Shell or enabling the extension?

**Comment by jehane** [comment]
I found this trace who seems relevant (with journalctl)

sept. 29 12:14:38 mallorne.workplace.fr gnome-session[6323]: Window manager warning: Trying to remove non-existent keybinding "show-hamster-dropdown".
sept. 29 12:14:38 mallorne.workplace.fr gnome-session[6323]: Gjs-Message: JS LOG: Extension "hamster@projecthamster.wordpress.com" had error: TypeError: this.extension is nu
sept. 29 12:14:38 mallorne.workplace.fr gnome-session[6323]: Gjs-Message: JS LOG: Extension "hamster@projecthamster.wordpress.com" had error: TypeError: St.Table is not a co
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: (gnome-shell:6444): Gjs-WARNING **: JS ERROR: TypeError: this.activityEntry is undefined
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: HamsterExtension.prototype._refresh@/home/mlombard/.local/share/gnome-shell/extensions/hamster@projecthamster.wo
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:90
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: (gnome-shell:6444): Gjs-WARNING **: JS ERROR: TypeError: this.activityEntry is undefined
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: HamsterExtension.prototype._refresh@/home/mlombard/.local/share/gnome-shell/extensions/hamster@projecthamster.wo
sept. 29 12:54:10 mallorne.workplace.fr gnome-session[6323]: _proxyInvoker/asyncCallback@resource:///org/gnome/gjs/modules/overrides/Gio.js:90

**Comment by moggers87** [comment]
Using Gnome's looking glass, I saw the error "St.Table is not a constructor". Looks like StTable got removed from the API; see [3.18 API docs](https://developer.gnome.org/st/3.18/) and [3.16 API docs](https://developer.gnome.org/st/3.16/).

After a bit of digging, I found [this Gnome Bugzilla entry](https://bugzilla.gnome.org/show_bug.cgi?id=703833). Looks like they've ported over their own code to use `ClutterTableLayout`.

Hope that helps!

**Comment by tbaugis** [comment]
Your pointers were an immense timesaver @moggers87 - thank you!
What's funny is that TableLayout itself has been deprecated for 2 years now in favour to grid layout, which i couldn't managed to make span full width, so for now just doing the same stuff gnome is.

@toupeira - the extension now works on 3.18 and should be good for pushing to extensions gnome.org

**Comment by toupeira** [comment]
@tbaugis thanks for the fix, release is pushed!

**Comment by ounos** [comment]
Using gnome 3.18, I get a **Loading...** next to hamster icon.
Executing journalctl -f as suggested, I get:
```
Okt 15 13:58:31 ounos gnome-session[349]: (gnome-shell:585): Gjs-WARNING **: JS ERROR: Exception in callback for signal: activate: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.gnome.Hamster.WindowServer was not provided by any .service files
Okt 15 13:58:31 ounos gnome-session[349]: _proxyInvoker@resource:///org/gnome/gjs/modules/overrides/Gio.js:98
Okt 15 13:58:31 ounos gnome-session[349]: _makeProxyMethod/<@resource:///org/gnome/gjs/modules/overrides/Gio.js:124
Okt 15 13:58:31 ounos gnome-session[349]: HamsterExtension.prototype._onShowHamsterActivate@/home/ounos/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/extension.js:498
Okt 15 13:58:31 ounos gnome-session[349]: _emit@resource:///org/gnome/gjs/modules/signals.js:124
Okt 15 13:58:31 ounos gnome-session[349]: PopupBaseMenuItem<.activate@resource:///org/gnome/shell/ui/popupMenu.js:164
Okt 15 13:58:31 ounos gnome-session[349]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Okt 15 13:58:31 ounos gnome-session[349]: PopupBaseMenuItem<._onButtonReleaseEvent@resource:///org/gnome/shell/ui/popupMenu.js:125
Okt 15 13:58:31 ounos gnome-session[349]: wrapper@resource:///org/gnome/gjs/modules/lang.js:169
Okt 15 13:58:48 ounos gnome-session[349]: (gnome-shell:585): Gjs-WARNING **: JS ERROR: TypeError:  is null
Okt 15 13:58:48 ounos gnome-session[349]: HamsterExtension.prototype._refresh@/home/ounos/.local/share/gnome-shell/extensions/hamster@projecthamster.wordpress.com/extension.js:343
```

**Comment by toupeira** [comment]
@ounos it looks like you don't have Hamster installed system-wide, are you using Git master and followed the installation instructions in the README?

**Comment by ounos** [comment]
omg, you are right. sorry about that.

**Comment by ford-prefect** [comment]
I don't see 3.18 support on extensions.gnome.org yet?

**Comment by toupeira** [comment]
@ford-prefect what do you mean exactly? [It's been online for a month now](https://extensions.gnome.org/review/5233).

**Comment by ford-prefect** [comment]
@toupeira I think this might be a local bug. When I opened https://extensions.gnome.org/extension/425/project-hamster-extension/ I saw an "OUTDATED" next to the extension. I hit the gear icon and it forced an install/update and now it looks fine.

p.s.: Thanks for the work on all of this!

**Comment by toupeira** [comment]
@ford-prefect yes the "outdated" refers to your local version ;-)

**Comment by ford-prefect** [comment]
<embarrased face> I got confused because the page was greyed, and I assumed that meant I couldn't update.
